[package]
name = "file-manager-backend"
version = "0.1.0"
edition = "2024"

[dependencies]
async-trait = "0.1.92"
axum = "0.8.9"
chrono = { version = "0.4.45", features = ["serde"] }
serde = { version = "1.0.229", features = ["derive"] }
sqlx = { version = "0.9.0", features = ["chrono", "runtime-tokio", "sqlite"] }
thiserror = "2.0.20"
tokio = "1.53.1"
